### PR TITLE
Prevent Cloudflare Rocket Loader deferring script

### PR DESCRIPTION
**Pull request by andreacassani**
When using Cloudflare with [Rocket Loader](https://developers.cloudflare.com/fundamentals/speed/rocket-loader/) enabled, the script injected by next-themes gets deferred causing the screen to flash.

As per [Cloudflare docs](https://developers.cloudflare.com/fundamentals/speed/rocket-loader/ignore-javascripts/), adding `data-cfasync="false"` to the `<script />` tag prevents this behavior from happening, and the flash doesn't happen anymore.

I don't know if this is the best solution, but since Cloudflare is quite common and Rocket Loader is enabled by default, this might be useful for people who want to keep it enabled or for those who don't actually know it will prevent next-themes from working properly.

### CODE REVIEW

**Comment by pacocoursey** [comment]
Not a fan of adding this universally – not everyone uses CloudFlare. But it would be better to support spreading props onto the `<script />` tag so you can just add it yourself.

**Comment by andreacassani** [comment]
> Not a fan of adding this universally – not everyone uses CloudFlare. But it would be better to support spreading props onto the `<script />` tag so you can just add it yourself.

Yes, you are totally right. I've added a new prop `scriptAttribute` to the `ThemeProvider` where we can pass attributes and their values down to the `<script />` element. I've also updated the readme with an example. Let me know what do you think

**Comment by nicholashamilton** [comment]
@andreacassani i'm using Cloudflare with Rocket Loader and could benefit from attribute on nicholashamilton.co

**Comment by alakhpc** [comment]
is there something blocking this? I believe this would be very useful.

**Comment by dollannn** [comment]
What is the status for this? What is blocking, are we looking for alternative solutions?

**Comment by patelvivekdev** [comment]
Thank you

Solved: https://github.com/pacocoursey/next-themes/issues/281#issuecomment-2094657762

**Review by pacocoursey — APPROVED** [review]

**Review by pacocoursey — APPROVED** [review]

**Pull request merged**
