### PR TITLE
Fixed "Do not add <script> tags using next/head" message in development mode

### LINKED ISSUE #84: "Do not add <script> tags using next/head" message in development mode
When next@12.0.11-canary.20 is used in development mode, there is a message in the console "Do not add <script> tags using next/head". So next@12.0.11 will also have this message.

Maybe use Script Component ( https://nextjs.org/docs/basic-features/script) instead of native script inside next/head.

### PR DESCRIPTION
**Pull request by km-mahbub**
Used Script from next/script. 

Closes #84

### CODE REVIEW

**Review by tronglongphung — COMMENTED** [review]
I think Script requires an id as well

**Comment by km-mahbub** [comment]
> I think Script requires an id as well

Oh yes. Added the id for nextjs to be able to optimize the script. Thanks

**Review by tronglongphung — APPROVED** [review]
lgtm

**Review by LordRonz — APPROVED** [review]
lgtm

**Comment by pacocoursey** [comment]
Thanks, but this isn't quite enough to fix it. Looking into it

**Pull request closed without merging**
