### PR TITLE
add option to use sessionStorage instead of localStorage

### PR DESCRIPTION
**Pull request by macguirerintoul**

### CODE REVIEW

**Comment by pacocoursey** [comment]
Thanks! I'd like to think about how to support this better than just a boolean. I wonder if we're missing any other common storage providers that would warrant this being a generic `cache` option. Or perhaps caching/syncing can be turned off entirely.

**Comment by trm217** [comment]
Don't you think having a generic option might be a bit over engineered for the common use cases?

I thought of the following implementation would solve #72 quiet nicely.
- Add a storage property: the accepted values are none : `none`, `sessionStorage`, `localStorage`.

Additionally I think it would be cool if it was possible to hook into the theme changes, to for example allow
the syncing of a users theme-preferences with a data-storage.

- For custom storage options we could define a simple interface. I believe something like this might make sense:
```ts
   interface ThemeStorage {
      get: () => Promise<string | null>
      set: (value: string) =>  Promise<void>
      delete: () => Promise<void>
      handleChange: EventEmitter
   }
```
An object implementing this interface could then be passed to the customStorage property to be used inside the ThemeProvider.

I think allowing the user to combine both the storage property and customStorage property could be very useful,
since saving a users preferences over multiple devices is fairly common.

**Comment by jasongerbes** [comment]
@pacocoursey, you could alternatively add a `storage?: 'local' | 'session' | Storage;` prop to `ThemeProvider` to allow for local/session/custom storage implementations:

```tsx
// localStorage (default)
function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider storage="local">
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
```

```tsx
// sessionStorage
function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider storage="session">
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
```

```tsx
// Custom storage implementation
const myCustomStorage: Storage = { /* Implementation here */ };

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider storage={myCustomStorage}>
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
```

**Comment by pacocoursey** [comment]
Closing in favor of the more recent work in #293

**Pull request closed without merging**
